title: Paradise Roleplay Pakistan
author: Desi Gabru
email: your-email@example.com
description: "The best GTA V Roleplay server in Pakistan!"
baseurl: ""
url: "https://saif33yk.github.io"

# Build settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-menus

sass:
  style: compressed

include:
  - _pages
  - _includes
  - _layouts
  - assets
  - assets/css

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
    sort_by: title
    sort_order: ascending

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
