title: Paradise Roleplay Pakistan
author: Desi Gabru
email: support@forestry.io
description: "Welcome to our roleplay server!"

baseurl: ""  # Fix: Removed /ubuild-jekyll
url: "https://saif33yk.github.io"  # Fix: Set correct GitHub Pages URL

# Build settings
defaults:
  - scope:
      path: ""  # Applies to all files
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-menus
