title: Paradise Roleplay Pakistan
description: "The most realistic GTA V Roleplay server in Pakistan!"
url: "https://saif33yk.github.io"
baseurl: ""
theme: jekyll-theme-minimal

collections:
  pages:
    output: true
    permalink: /:path/
    sort_by: title

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
      show_in_nav: true
  - scope:
      path: ""
    values:
      layout: "default"

plugins: [jekyll-feed, jekyll-menus]
exclude: [Gemfile, Gemfile.lock, README.md]
