title: Paradise Roleplay Pakistan
author: Desi Gabru
email: support@forestry.io
url: "https://saif33yk.github.io"
description: "Hi"

theme: jekyll-theme-minimal

# Build settings
baseurl: ""  # Fix: Removed /ubuild-jekyll
defaults:
  - scope:
      path: ""  # an empty string here means all files in the project
    values:
      layout: "default"  # This ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus
